FROM python:latest

WORKDIR /home/app

RUN apt update && apt upgrade -y
RUN apt install -y  build-essential software-properties-common libpq-dev make postgresql-client gettext cron nano

COPY requirements/ /home/app/requirements/

RUN pip3 install --no-cache-dir -r /home/app/requirements/development.txt
COPY . .

EXPOSE 8000